### ISSUE TITLE
Unable to install on Ubuntu in WSL

### ISSUE THREAD

**Issue by Hexadecimalz** [georgbuechner/dissonance#35]
Hello is this compatible with WSL on Windows on Ubuntu 20? I have run the following commands based on your documentation, but am not making any progress. Have I missed a critical step? 
```
sudo apt-get install aubio-tools libaubio-dev libaubio-doc
sudo apt install build-essential cmake python
sudo apt install python3-pip
pip install conan
git clone https://github.com/georgbuechner/dissonance
cd dissonance/ 
make aubio
make install 

make install
make build -B
make[1]: Entering directory '/home/hex/dissonance'
# Create build folder and install conan-dependencies.
rm -rf build; mkdir build
cd build && conan install .. --build=missing -s compiler.libcxx=libstdc++11
/bin/sh: 1: conan: not found
make[1]: *** [Makefile:35: build] Error 127
make[1]: Leaving directory '/home/hex/dissonance'
make: *** [Makefile:58: install] Error 2
```
I attempted the command to remove the build directory. `conan install` and everything thereafter is unsuccessful to run. I verified that conan is present via pip. 
```
pip list 
-------------------------
conan                  1.42.0

```

**Comment by georgbuechner** [comment]
First of: 
I acctually installed it on WSL, however, there always remain the following two problems:
1. Playing audio: audio can not nativly be played, you kinda need to "forward" audio from WSL to windows: https://www.reddit.com/r/bashonubuntuonwindows/comments/hrn1lz/wsl_sound_through_pulseaudio_solved/
2. Displaying unicode: some unicode characters are not displayed correctly, mainly the "&#22C5;"  character, which is very very annoying

To your specific issue: oviously the problem is, that conan is not found, altough conan seems to be present. That never happed too me, so I cannot really help. What is the output of `conan --version` and `whereis conan`?

**Comment by georgbuechner** [comment]
Oh also, when running with ubuntu (or any debain based distro), the `apt get aubio...` step is enough, and you need not (and probably should not) also run the `make aubio` step.

**Comment by georgbuechner** [comment]
Okay, using ubunto 20 with WSL I got a similar error, and the reason was, that conan was install to `$HOME/.local/bin` which was not in `$PATH`. 

running 
```
export PATH=$PATH:$HOME/.local/bin
```

solved the issue.

**Comment by georgbuechner** [comment]
Okay, so I also updated the dot-symbol to be compatible with Windows. Sound is still not playing, and once the game starts the screen is flushed with loads of error. However, you can simply press q (exist) and then select (don't exist) or press 'd' to open resource distribution and the 'q' again, to refresh the screen. And from then on the game is or should be fully playable on Windows with WSL. Let me know if this worked for you. 

You should update the cope, i.e. `git pull`

**Comment by Hexadecimalz** [comment]
Thanks those fixes worked. I updated the repo and exported the path, and afterward compile worked fine. I had not realized WSL was not forwarding audio by default, so in the interest of time I will continue with a VM.
